version: '3'
services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - S3_ENDPOINT_URL="http://localhost:4566"
      - AWS_ACCESS_KEY_ID="localstack"
      - AWS_SECRET_ACCESS_KEY="localstack"
    ports:
      - '4566:4566'
    volumes:
      - './localstack:/tmp/localstack'
    command: 'infra start'
